In [1]:
import numpy as np
import pandas as pd
import shutil

from_file = open("data/reddit.csv","r")
to_file = open("data/reddit_.csv", "w")
from_file.readline()
to_file.write(line)
shutil.copyfileobj(from_file, to_file)
from_file.close()
to_file.close()

from_file = open("data/reddit.csv","r")
line = from_file.readline()
line = from_file.readline()
from_file.close()

In [2]:
data = pd.read_csv("data/mooc.csv", header=0, index_col=False)
data

,user_id,item_id,timestamp,state_label,0,1,2,3
0,0,0,0,0,-0.319991,-0.435701,0.106784,-0.067309
1,0,1,6,0,-0.319991,-0.435701,0.106784,-0.067309
2,0,2,41,0,-0.319991,-0.435701,0.106784,-0.067309
3,0,1,49,0,-0.319991,-0.435701,0.106784,-0.067309
4,0,2,51,0,-0.319991,-0.435701,0.106784,-0.067309
...,...,...,...,...,...,...,...,...
411744,7026,8,2572041,0,-0.319991,-0.435701,0.106784,-0.067309
411745,6842,8,2572043,0,-0.319991,-0.435701,0.106784,-0.067309
411746,7026,9,2572048,0,-0.319991,-0.435701,0.106784,-0.067309
411747,6842,5,2572054,0,-0.319991,-0.435701,0.106784,-0.067309
411748,70,23,2572086,0,-0.319991,-0.435701,0.106784,-0.067309

In [3]:
rates = [0.1, 0.05, 0.01, 0.005]
percents = ["10", "5", "1", "0.5"]
for rate, percent in zip(rates, percents):
    for i in range(10):
        drop_indices = np.random.choice(data.index, int(len(data)*(1-rate)), replace=False)
        data1 = data.drop(drop_indices).reset_index(drop=True)
        data1.to_csv("data/mooc/mooc" + str(percent) + "%_" + str(i) + ".csv", index=False)
    data1 = data[:int(len(data) * rate)]
    data1.to_csv("data/mooc/mooc" + str(percent) + "%_10.csv", index=False)

user = data["user_id"].value_counts()
data = data[data.user_id.isin(list(user[user > 10].index))]
data

i = 0
while i < 10:
    print("=========", i, "=========")
    drop_indices = np.random.choice(data.index, int(len(data)*0.8), replace=False)
    data1 = data.drop(drop_indices).reset_index(drop=True)
    if len(set(data1["user_id"])) != len(set(data["user_id"])) or len(set(data1["item_id"])) != len(set(data["item_id"])):
        print(len(set(data1["user_id"])), len(set(data["user_id"])))
        print(len(set(data1["item_id"])), len(set(data["item_id"])))
    else:
        print(len(set(data1["user_id"])), len(set(data["user_id"])))
        print(len(set(data1["item_id"])), len(set(data["item_id"])))
        data1.to_csv("data/lastfm20%_" + str(i) + ".csv", index=False)
        i += 1

data.to_csv("data/lastfm20%.csv", index=False)

pd.read_csv("data/lastfm20%_1.csv", header=0, index_col=False)

In [5]:
pd.read_csv("data/wikipedia10%_0.csv", header=0, index_col=False)

,user_id,item_id,timestamp,state_label,0,1,2,3,4,5,...,162,163,164,165,166,167,168,169,170,171
0,1,1,77,0,-0.175063,-0.176678,-0.937091,-0.381926,0,-0.636535,...,-0.090115,-0.096068,-0.068136,-0.060835,-0.058394,-0.062079,-0.044674,-0.050464,-0.041448,-0.038775
1,1,1,150,0,-0.175063,-0.176678,-0.937091,-0.381926,0,-0.636535,...,-0.090115,-0.096068,-0.068136,-0.060835,-0.058394,-0.062079,-0.044674,-0.050464,-0.041448,-0.038775
2,3,3,169,0,-0.090439,-0.086761,0.929211,0.198779,0,0.000822,...,-0.090115,-0.096068,-0.068136,-0.060835,-0.058394,-0.062079,-0.044674,-0.050464,-0.041448,-0.038775
3,1,1,300,0,-0.175063,-0.176678,-0.937091,-0.381926,0,-0.636535,...,-0.090115,-0.096068,-0.068136,-0.060835,-0.058394,-0.062079,-0.044674,-0.050464,-0.041448,-0.038775
4,8,7,395,0,-0.175063,-0.176678,-0.937091,-0.381926,0,-0.636535,...,-0.090115,0.950651,-0.068136,-0.060835,-0.058394,7.335416,-0.044674,-0.050464,-0.041448,-0.038775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15743,691,71,2677574,0,-0.175063,-0.176678,-0.937091,-0.381926,0,-0.636535,...,-0.090115,-0.096068,-0.068136,-0.060835,-0.058394,-0.062079,-0.044674,-0.050464,-0.041448,-0.038775
15744,5321,682,2677595,0,-0.129930,-0.130169,1.282424,-0.381926,0,0.525705,...,-0.090115,-0.096068,-0.068136,-0.060835,-0.058394,-0.062079,-0.044674,13.150104,-0.041448,-0.038775
15745,1007,310,2677633,0,-0.175063,-0.176678,-0.937091,-0.381926,0,-0.636535,...,-0.090115,-0.096068,-0.068136,-0.060835,-0.058394,-0.062079,-0.044674,-0.050464,-0.041448,-0.038775
15746,5299,882,2677738,0,-0.056589,-0.058856,1.285865,-0.381926,0,1.201426,...,-0.090115,-0.096068,-0.068136,-0.060835,-0.058394,-0.062079,-0.044674,-0.050464,-0.041448,-0.038775
15747,963,486,2677791,0,-0.160959,-0.161175,-0.937091,3.618481,0,-0.636535,...,-0.090115,-0.096068,-0.068136,-0.060835,-0.058394,-0.062079,-0.044674,-0.050464,-0.041448,-0.038775